---

ignore-failures:

    python:
        - alabaster
        - async-generator
        - async-timeout
        - blinker
        - click-completion
        - click-configfile
        - click-default-group
        - click-didyoumean
        - click-log
        - click-repl
        - click-threading
        - cycler
        - doublemetaphone
        - entrypoints
        - ipython-genutils
        - markupsafe
        - mccabe
        - mistune
        - patsy
        - pickleshare
        - probableparsing
        - probablepeople
        - pylev
        - send2trash
        - sphinxcontrib-jsmath
        - testpath
        - vobject
        - webencodings
